name: AutoencoderLDM_02x10x_0.1B
target: ldm.models.wrapper.beta_vae-t2i.BVaeLDMWrapper     # Wrapper to use LDM Autoencder pre-trained model    
params:
  ckpt_path: logs_dir/imnet256/beta-vae-skipViT-b-2/imagenet256_hdf5_v0/0.20x-1.0x-0.1b/2025-06-21/manual/V0/2025-07-06/101646/checkpoints/last.ckpt   #logs_dir/imnet256/beta-vae-skipViT-S-2/imagenet256_hdf5_v0/baseline/0.50x-1.00x-0.1b/2025-05-10/27587/checkpoints/last.ckpt
  # (x0.2 -> x1.0)