name: AutoencoderLDM_05x05x_0.5B_Baseline
target: ldm.models.wrapper.beta_vae-t2i.BVaeLDMWrapper     # Wrapper to use LDM Autoencder pre-trained model    
params:
  ckpt_path: logs_dir/imnet256/beta-vae-skipViT-b-2/imagenet256_hdf5_v2/0.50x-0.50x-5.0b/2025-06-21/manual/V2/2025-06-21/29852/checkpoints/last.ckpt
  # (Baseline model x0.5 -> x0.5)