name: AutoencoderLDM_05x05x_1e-4B_Baseline
target: ldm.models.wrapper.beta_vae-t2i.BVaeLDMWrapper     # Wrapper to use LDM Autoencder pre-trained model    
params:
  ckpt_path: logs_dir/imnet256/beta-vae-skipViT-S-2/imagenet256_hdf5_v0/baseline/0.50x-0.50x-1e-4b/2025-05-09/27501/checkpoints/last.ckpt
  # (Baseline model x0.5 -> x0.5)