name: DiT-XL-2
# Flow Model (SiT)
target: ldm.frameworks.rectified_flow.fm.RectifiedFlowModel
params:
  schedule: linear
  sigma_min: 0.0
  net_cfg:
    target: ldm.models.wrapper.dit_context.DiTLDMWrapper
    params:
      in_channels: 4
      input_size: 32
      depth: 28
      hidden_size: 1152
      patch_size: 2
      num_heads: 16
      context_size: 1024
      cat_context: True
      num_classes: 1000                   # Defines class label embedding, default: -1, for None (1000 classes for ImageNet)
      context_dropout_prob: 0.1           # 0.0: no dropout, 0.1: 10% dropout of context vector in batch
      class_dropout_prob: 0.1             # 0.0: no dropout, 0.1: 10% dropout of class label
      learn_sigma: False                  # trained without sigma
      compile: True
      ckpt_path: checkpoints/SiT-XL-2-256x256.pt
